apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: stream1.punecloud.in           #Host based routing
    http:
      paths:    
      - pathType: Prefix
        path: /
        backend:
          service:
            name: my-service-demo
            port:
              number: 80

 # how to do path based routing, just uncomment below section and comment out host based routing section
 # - host: punecloud.in           #path based routing
 #   http:
 #     paths:    
 #     - pathType: Prefix
 #       path: /steam1
 #       backend:
 #         service:
 #           name: my-service-demo
 #           port:
 #             number: 80
